COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= fifo_full_xyz_data_sensortime.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bma400.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk